implemented modal to work with galleryMini and incorporated carousel
Smelser-Squad/FindMyParadise pull request #194
Opened 2021-04-01 21:10 UTC by VictorBarronG

works and pops up, still need to pass data between components and connect to backend.
Please ignore the event.java file and the package.json. wasn't sure how to remove that

2021-04-01 21:14 UTC, tamera-brown approved these changes

2021-04-01 21:15 UTC, tamera-brown commented
You have to remove package-lock.json manually

2021-04-01 21:39 UTC, tamera-brown requested changes
Remove package-lock.json

2021-04-02 13:22 UTC, kpugh97 submitted a review, later dismissed

2021-04-02 14:16 UTC, Jason-Williams-github approved these changes

2021-04-02 14:46 UTC, StephenDMay approved these changes

2021-04-02 14:47 UTC, StephenDMay approved these changes

2021-04-02 16:40 UTC, tamera-brown approved these changes

2021-04-02 18:54 UTC, closed without merging